export const ENTITY_GET = 'ENTITY_GET';
export const ENTITY_GET_SUCCESS = 'ENTITY_GET_SUCCESS';
export const ENTITY_GET_ERROR = 'ENTITY_GET_ERROR';
export const ENTITY_GET_ERROR_LATEST = 'ENTITY_GET_ERROR_LATEST';
export const ENTITY_REMOVE = 'ENTITY_REMOVE';
export const ENTITY_CONGRATS = 'ENTITY_CONGRATS';
